baseURL: 'https://liaminwards.com/'
languageCode: en-us
title: Liam Inwards
theme: PaperMod
outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  author: Liam Inwards
  homeInfoParams:
      Title: Welcome on my *Musings* page! 👋
      Content: I regularly publish Musings, mainly about personal development and philosophy. If you are interested in these topics, you are welcome to subscribe to my [**newsletter 🡕**](/newsletter), where you will receive all my Musings straight in your email.

  socialIcons: # optional
      - name: "RSS"
        url: "index.xml"
      - name: "Twitter"
        url: "https://twitter.com/liam_inw"
      - name: "buymeacoffee"
        url: "https://www.buymeacoffee.com/liaminwards"
  disableScrollToTop: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  ShowPostNavLinks: true

menu:
  main:
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 10
    - identifier: newsletter
      name: Newsletter
      url: /newsletter/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 30

